---
- name:               Build APIC Configuration from Scratch
  hosts:              apic
  connection:         local
  gather_facts:       no
  vars:
    apic_info:        &apic_info
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
      validate_certs: no
    shared_vars:
      descr:                    "Created by Ansible"

  tasks:
  - name: TASK 01 - Create Tenant
    aci_tenant:
      <<: *apic_info
      tenant: "{{ tenant }}"
      state: present

  - name: TASK 02 - Create VRF
    aci_vrf:
      <<: *apic_info
      tenant: "{{ tenant }}"
      vrf: "{{ vrf }}"
      description: "{{ shared_vars.descr }}"
      state: "present"

  - name: TASK 03 - Create BRIDGE DOMAIN
    aci_bd:
      <<: *apic_info
      tenant: "{{ tenant }}"
      bd: "{{ item.bd }}"
      vrf: "{{ vrf }}"
      description: "{{ shared_vars.descr }}"
      state: "present"
    with_items: "{{ bds }}"

  - name: TASK 04 - Create BRIDGE DOMAIN SUBNET
    aci_bd_subnet:
      <<: *apic_info
      state: "present"
      tenant: "{{ tenant }}"
      bd: "{{ item.bd }}"
      gateway: "{{ item.gateway }}"
      mask: "{{ item.mask }}"
    with_items: "{{ bds }}"

  - name: Create APPLICATION PROFILE
    aci_ap:
      <<: *apic_info
      tenant: "{{ tenant }}"
      ap: "{{ ap }}"
      state: present

  - name: Create EPG
    aci_epg:
      <<: *apic_info
      tenant: "{{ tenant }}"
      ap: "{{ ap }}"
      epg: "{{ item.epg }}"
      bd: "{{ item.bd }}"
      description: "{{ shared_vars.descr }}"
      state: present
    with_items: "{{ epgs }}"

  - name: TASK 10 - Create APPLICATION PROFILE
    aci_ap:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      state: "present"
      validate_certs: False
      tenant: "{{ tenant }}"
      ap: "{{ ap }}"
      descr: "App Profile Created Using Ansible"

  - name: TASK 11 - Create APPLICATION EPGS
    aci_epg:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      state: "present"
      validate_certs: False
      tenant: "{{ tenant }}"
      ap: "{{ ap }}"
      epg: "{{ item.epg }}"
      bd: "{{ item.bd }}"
      description: "EPG Created Using Ansible"
    with_items: "{{ epgs }}"

  - name: Task 12 - BOND EPGs to DOMAIN
    aci_epg_to_domain:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      state: "present"
      validate_certs: false
      tenant: "{{ tenant }}"
      ap: "{{ ap }}"
      epg: "{{ item.epg }}"
      domain: "ATX_Physdom"
      domain_type: "phys"
#      vm_provider: "vmware"
      encap_mode: "auto"
#      encap: "{{ item.encap }}"
    with_items: "{{ epgs }}"

  - name: Task 13 - Associate EPGs to CONTRACTS
    aci_epg_to_contract:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      state: "present"
      validate_certs: False
      tenant: "{{ tenant }}"
      ap: "{{ ap }}"
      epg: "{{ item.epg }}"
      contract: "{{ item.contract }}"
      contract_type: "{{ item.contract_type }}"
    with_items: "{{ epg_contracts }}"

  - name : Task 14 - EPG Static Path Binding
    aci_static_binding_to_epg:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      state: "present"
      validate_certs: False
      pod_id: "{{ item.pod }}"
      tenant: "{{ tenant }}"
      ap: "{{ ap }}"
      description: "{{ item.ServerName }}"
      epg: "{{ item.epg }}"
      encap_id: "{{ item.encap }}"
      leafs: "{{ item.leaf }}"
      interface:  "{{ item.interface }}"
    with_items: "{{ static_bind }}"
