---
- name:               Build APIC Configuration from Scratch
  hosts:              apic
  connection:         local
  gather_facts:       no
  vars:
    apic_info:        &apic_info
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
      validate_certs: no
    shared_vars:
      descr:                    "Created by Ansible"

  tasks:
  - name: Pre1 - Create VLAN Pools
    aci_vlan_pool:
      <<: *apic_info
      pool: "{{ vlan_pools.vlanName }}"
      pool_allocation_mode: "{{ vlan_pools.allocMode }}"
      description: "{{ vlan_pools.description }}"
      state: present

  - name: Pre2 - Assign VLAN encap blocks
    aci_vlan_pool_encap_block:
      <<: *apic_info
      pool: "{{ vlan_pools.vlanName }}"
      pool_allocation_mode: "{{ vlan_pools.allocMode }}"
      block_name: "{{ vlan_pools.blockName }}"
      block_start: "{{ vlan_pools.vlanFrom }}"
      block_end: "{{ vlan_pools.vlanTo }}"
      state: present

  - name: Pre3 - Create Physical Domain
    aci_domain:
      <<: *apic_info
      domain: "{{ phys_dom.physDomName }}"
      domain_type: phys
      state: present

  - name: Pre4 - Bind a physical domain to VLAN pool
    aci_domain_to_vlan_pool:
      <<: *apic_info
      domain: "{{ phys_dom.physDomName }}"
      domain_type: phys
      pool: "{{ vlan_pools.vlanName }}"
      pool_allocation_mode: "{{ vlan_pools.allocMode }}"
      state: present

  - name: Pre5 - Create Attachable Access Entity Profile
    aci_aep:
      <<: *apic_info
      aep: "{{ aaep.aaepName }}"
      infra_vlan: true
      state: present

  - name: Pre6 - Add AEP to domain binding
    aci_aep_to_domain: 
      <<: *apic_info
      aep: "{{ aaep.aaepName }}"
      domain: "{{ phys_dom.physDomName }}"
      domain_type: phys
      state: present

  - name: Pre7 - Create a Leaf Access Port Policy Group
    aci_interface_policy_leaf_policy_group:
      <<: *apic_info
      lag_type: leaf
      policy_group: "{{ item.PolName }}"
#      link_level_policy: "{{  }}"
      aep: "{{ item.AEP }}"
      state: present
    with_items: "{{ intf_policies }}"
    loop_control:
      pause: .5

  - name: Pre8 - Add a new leaf_interface_profile
    aci_interface_policy_leaf_profile:
      <<: *apic_info
      leaf_interface_profile: "{{ interfaceSelectors.ifPolicyLeafProfileName }}"
      description: "{{ interfaceSelectors.description }}"
      state: present

  - name: Pre9 - Associate an Interface Access Port Selector to an Interface Policy Leaf Profile with a Policy Group
    aci_access_port_to_interface_policy_leaf_profile:
      <<: *apic_info
      leaf_interface_profile: "{{ interfaceSelectors.ifPolicyLeafProfileName }}"
      access_port_selector:  "{{ interfaceSelectors.accessPortSelector }}"
      leaf_port_blk:  "{{ interfaceSelectors.blockName }}"
      from_port: "{{ interfaceSelectors.fromPort }}"
      to_port: "{{ interfaceSelectors.toPort }}"
      policy_group: "{{ interfaceSelectors.intf_policy }}"
      state: present

  - name: Pre10 - creating a Leaf Profile with description
    aci_switch_policy_leaf_profile:
      <<: *apic_info
      leaf_profile: "{{ item.swPolicyLeafProfileName}}"
      description: sw_description
      state: present
    with_items: "{{ swPolicyLeafProfiles}}"
    loop_control:
      pause: .5

  - name: Pre 11 adding a switch policy leaf profile selector associated Node Block range
    aci_switch_leaf_selector:
      <<: *apic_info
      leaf_profile: "{{ item.swPolicyLeafProfileName}}"
      leaf: "{{ item.leafName}}"
      leaf_node_blk: "{{ item.swPolicyLeafProfileName}}"
      from: "{{ item.leafId}}"
      to: "{{ item.leafId}}"
      state: present
    with_items: "{{ swPolicyLeafProfiles}}"
    loop_control:
      pause: .5 

  - name: Associating an interface selector profile to a switch policy leaf profile
    aci_interface_selector_to_switch_policy_leaf_profile:
      <<: *apic_info
      leaf_profile: "{{ item.swPolicyLeafProfileName}}"
      interface_selector: "{{ item.intProfileName}}"
      state: present
    with_items: "{{ LeafProfileInterfaceSelectors}}"
    loop_control:
      pause: .5 
