---
- name:               Build APIC Configuration from Scratch
  hosts:              apic
  connection:         local
  gather_facts:       no
  vars:
    shared_vars:
      descr:                    "Created by Ansible"
    tenant: Demo

  tasks:
  - name: Create Tenant
    aci_tenant:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
      validate_certs: no
      tenant: "{{tenant}}"
      state: present