---
- name:               Build APIC Configuration from Scratch
  hosts:              apic1
  connection:         local
  gather_facts:       no
  vars:
    apic_info:        &apic_info
      host:           "{{ apic_ip }}"
      username:       "{{ apic_username }}"
      password:       "{{ apic_password }}"

    shared_vars:
      descr:                    "Created by Ansible"

    tenants:
    - tenantName: Demo


  - name: Create Tenant
    aci_tenant:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      tenant: "{{item.tenantName}}"
      state: present
    with_items:
      "{{tenants}}"
    loop_control:
      pause: .5